config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :movie
    belongs_to :list
    validates :list_id, uniqueness: { scope: :movie_id,
        message: "already bookmarked" }
    validates :comment,  length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/movie.rb
class Movie < ApplicationRecord
    before_destroy :ensure_no_children

    has_many :bookmarks, dependent: :restrict_with_error
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true

    private

    def ensure_no_children
      unless self.bookmarks.empty?
        raise ActiveRecord::InvalidForeignKey
        raise ActiveRecord::Rollback
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def new
        @list = List.find(params[:list_id])
        @bookmark = Bookmark.new
    end
    
    def create
        @comment = params[:bookmark][:comment]
        @list = List.find(params[:list_id])
        @movies = Movie.where(id: params.dig(:bookmark, :movie))
        return render_new if @movies.empty?
    
        ActiveRecord::Base.transaction do
          @movies.each do |movie|
            bookmark = Bookmark.new(comment: @comment, list: @list, movie: movie)
            bookmark.save!
          end
          redirect_to list_path(@list)
        end
      rescue ActiveRecord::RecordInvalid
        render_new
    end

    def destroy
        @bookmark = Bookmark.find(params[:id])
        @bookmark.destroy
        redirect_to list_path(@bookmark.list), status: :see_other
      end
    
    private
    
    def render_new
        @bookmark = Bookmark.new
        @bookmark.errors.add(:base, "A selected already exists")
        render :new, status: :unprocessable_entity
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: %i[ show edit update destroy ]

    def index
      @lists = List.all
    end
    
    def show
      @bookmarks = @list.bookmarks
      @bookmark = Bookmark.new
    end

    def new
      @list = List.new
    end

    def create
      @list = List.new(list_params)
      respond_to do |format|
        if @list.save
          format.html { redirect_to list_url(@list), notice: "List was successfully created." }
          format.json { render :show, status: :created, location: @list }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @list.errors, status: :unprocessable_entity }
        end
      end
    end
    
    private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
        params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.input :movie,
          collection: Movie.all,
          input_html: {multiple: true, data: {controller: "tom-select"}},
          include_hidden: false
        %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render "form", bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Back to my list", list_path(@list) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>

</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show all bookmarks to this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
</div>
<%# cinema-background_01 %>
<div class="container">
  <div class="row mt-5">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bookmark.movie.poster_url %>')">
          <%= bookmark.comment %>
          <%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
      </div>
    <% end %>
    <div class="card-tags">
      <%= link_to "add", new_list_bookmark_path(@list) %>
    </div>
    <div class="card-tags">
      <%= link_to "back to lists", lists_path %>
    </div>
  </div>
</div>